import { SnippetDocShell, type SnippetDoc } from "../SnippetDocShell";

const doc: SnippetDoc = {
  slug: `bf-stock`,
  head: `BloxFruits`,
  word: `Stock.`,
  tail: ``,
  badge: `utility`,
  tags: [
    { icon: `fa-brands fa-discord`, label: `BDFD` },
  ],
  subtitle: `This snippet lets you run an API-based command which shows \`Bloxfruit's\` normal and mirage stock at that specific time.`,
  info: [
    { head: `// how to use`, body: `Add the command with its respective trigger in your app. Avoid modifying anything unless you know what you're doing. Make sure to include the API key you get from \`RapidAPI\`. Important: Make sure to upload all 41 fruit emojis to your bot's emoji list (in the Developer Portal), then copy and paste each emoji's ID into the corresponding variable in the code.` },
    { head: `// credits`, body: `All credits go to the creator of the API, Menwiz.` },
  ],
  files: [
    { name: `!stock`, lang: `bdfd`, code: `$nomention
$c[ADD THE API KEY FROM RAPID API HERE]
$httpAddHeader[x-rapidapi-key;API_KEY_HERE]
$httpAddHeader[x-rapidapi-host;blox-fruit-stock-fruit.p.rapidapi.com]
$httpGet[https://blox-fruit-stock-fruit.p.rapidapi.com/]

$c[ADD THE EMOJI IDs RESPECTIVELY FROM 1 TO 41]
$var[id1;ID_HERE] $c[ID should be of the rocket fruit]
$var[id2;]
$var[id3;]
$var[id4;]
$var[id5;]
$var[id6;]
$var[id7;]   $c[ID should be of the flame fruit]
$var[id8;]
$var[id9;]
$var[id10;]
$var[id11;]
$var[id12;]
$var[id13;]
$var[id14;]   $c[ID should be of the light fruit]
$var[id15;]
$var[id16;]
$var[id17;]
$var[id18;]
$var[id19;]
$var[id20;]
$var[id21;]   $c[ID should be of the creation fruit]
$var[id22;]
$var[id23;]
$var[id24;]
$var[id25;]
$var[id26;]
$var[id27;]
$var[id28;]   $c[ID should be of the blizzard fruit]
$var[id29;]
$var[id30;]
$var[id31;]
$var[id32;]
$var[id33;]
$var[id34;]
$var[id35;]   $c[ID should be of the control fruit]
$var[id36;]
$var[id37;]
$var[id38;]
$var[id39;]
$var[id40;]
$var[id41;]

$if[$message==]
Usage: \`!stock {normal or mirage}\`

$elseif[$toLowercase[$message]==normal]
$var[a;$replaceText[$httpResult[normalStock];[;]]
$var[b;$replaceText[$var[a];";]]
$var[c;$replaceText[$var[b];\\];]]
$textSplit[$var[c];,]

$var[fruit1;$if[$splitText[1]==Rocket]<:Rocket:$var[id1]> Rocket$elseif[$splitText[1]==Spin]<:Spin:$var[id2]> Spin$elseif[$splitText[1]==Blade]<:Blade:$var[id3]> Blade$elseif[$splitText[1]==Spring]<:Spring:$var[id4]> Spring$elseif[$splitText[1]==Bomb]<:Bomb:$var[id5]> Bomb$elseif[$splitText[1]==Smoke]<:Smoke:$var[id6]> Smoke$elseif[$splitText[1]==Spike]<:Spike:$var[id7]> Spike$elseif[$splitText[1]==Flame]<:Flame:$var[id8]> Flame$elseif[$splitText[1]==Ice]<:Ice:$var[id9]> Ice$elseif[$splitText[1]==Sand]<:Sand:$var[id10]> Sand$elseif[$splitText[1]==Dark]<:Dark:$var[id11]> Dark$elseif[$splitText[1]==Eagle]<:Eagle:$var[id12]> Eagle$elseif[$splitText[1]==Diamond]<:Diamond:$var[id13]> Diamond$elseif[$splitText[1]==Light]<:Light:$var[id14]> Light$elseif[$splitText[1]==Rubber]<:Rubber:$var[id15]> Rubber$elseif[$splitText[1]==Ghost]<:Ghost:$var[id16]> Ghost$elseif[$splitText[1]==Magma]<:Magma:$var[id17]> Magma$elseif[$splitText[1]==Quake]<:Quake:$var[id18]> Quake$elseif[$splitText[1]==Buddha]<:Buddha:$var[id19]> Buddha$elseif[$splitText[1]==Love]<:Love:$var[id20]> Love$elseif[$splitText[1]==Creation]<:Creation:$var[id21]> Creation$elseif[$splitText[1]==Spider]<:Spider:$var[id22]> Spider$elseif[$splitText[1]==Sound]<:Sound:$var[id23]> Sound$elseif[$splitText[1]==Phoenix]<:Phoenix:$var[id24]> Phoenix$elseif[$splitText[1]==Portal]<:Portal:$var[id25]> Portal$elseif[$splitText[1]==Rumble]<:Rumble:$var[id26]> Rumble$elseif[$splitText[1]==Pain]<:Pain:$var[id27]> Pain$elseif[$splitText[1]==Blizzard]<:Blizzard:$var[id28]> Blizzard$elseif[$splitText[1]==Gravity]<:Gravity:$var[id29]> Gravity$elseif[$splitText[1]==Mammoth]<:Mammoth:$var[id30]> Mammoth$elseif[$splitText[1]==T-Rex]<:TRex:$var[id31]> T-Rex$elseif[$splitText[1]==Dough]<:Dough:$var[id32]> Dough$elseif[$splitText[1]==Shadow]<:Shadow:$var[id33]> Shadow$elseif[$splitText[1]==Venom]<:Venom:$var[id34]> Venom$elseif[$splitText[1]==Control]<:Control:$var[id35]> Control$elseif[$splitText[1]==Gas]<:Gas:$var[id36]> Gas$elseif[$splitText[1]==Spirit]<:Spirit:$var[id37]> Spirit$elseif[$splitText[1]==Leopard]<:Leopard:$var[id38]> Leopard$elseif[$splitText[1]==Yeti]<:Yeti:$var[id39]> Yeti$elseif[$splitText[1]==Kitsune]<:Kitsune:$var[id40]> Kitsune$elseif[$splitText[1]==Dragon]<:EasternDragon:$var[id41]> Dragon$endif]
$var[fruit2;$if[$splitText[2]==Rocket]<:Rocket:$var[id1]> Rocket$elseif[$splitText[2]==Spin]<:Spin:$var[id2]> Spin$elseif[$splitText[2]==Blade]<:Blade:$var[id3]> Blade$elseif[$splitText[2]==Spring]<:Spring:$var[id4]> Spring$elseif[$splitText[2]==Bomb]<:Bomb:$var[id5]> Bomb$elseif[$splitText[2]==Smoke]<:Smoke:$var[id6]> Smoke$elseif[$splitText[2]==Spike]<:Spike:$var[id7]> Spike$elseif[$splitText[2]==Flame]<:Flame:$var[id8]> Flame$elseif[$splitText[2]==Ice]<:Ice:$var[id9]> Ice$elseif[$splitText[2]==Sand]<:Sand:$var[id10]> Sand$elseif[$splitText[2]==Dark]<:Dark:$var[id11]> Dark$elseif[$splitText[2]==Eagle]<:Eagle:$var[id12]> Eagle$elseif[$splitText[2]==Diamond]<:Diamond:$var[id13]> Diamond$elseif[$splitText[2]==Light]<:Light:$var[id14]> Light$elseif[$splitText[2]==Rubber]<:Rubber:$var[id15]> Rubber$elseif[$splitText[2]==Ghost]<:Ghost:$var[id16]> Ghost$elseif[$splitText[2]==Magma]<:Magma:$var[id17]> Magma$elseif[$splitText[2]==Quake]<:Quake:$var[id18]> Quake$elseif[$splitText[2]==Buddha]<:Buddha:$var[id19]> Buddha$elseif[$splitText[2]==Love]<:Love:$var[id20]> Love$elseif[$splitText[2]==Creation]<:Creation:$var[id21]> Creation$elseif[$splitText[2]==Spider]<:Spider:$var[id22]> Spider$elseif[$splitText[2]==Sound]<:Sound:$var[id23]> Sound$elseif[$splitText[2]==Phoenix]<:Phoenix:$var[id24]> Phoenix$elseif[$splitText[2]==Portal]<:Portal:$var[id25]> Portal$elseif[$splitText[2]==Rumble]<:Rumble:$var[id26]> Rumble$elseif[$splitText[2]==Pain]<:Pain:$var[id27]> Pain$elseif[$splitText[2]==Blizzard]<:Blizzard:$var[id28]> Blizzard$elseif[$splitText[2]==Gravity]<:Gravity:$var[id29]> Gravity$elseif[$splitText[2]==Mammoth]<:Mammoth:$var[id30]> Mammoth$elseif[$splitText[2]==T-Rex]<:TRex:$var[id31]> T-Rex$elseif[$splitText[2]==Dough]<:Dough:$var[id32]> Dough$elseif[$splitText[2]==Shadow]<:Shadow:$var[id33]> Shadow$elseif[$splitText[2]==Venom]<:Venom:$var[id34]> Venom$elseif[$splitText[2]==Control]<:Control:$var[id35]> Control$elseif[$splitText[2]==Gas]<:Gas:$var[id36]> Gas$elseif[$splitText[2]==Spirit]<:Spirit:$var[id37]> Spirit$elseif[$splitText[2]==Leopard]<:Leopard:$var[id38]> Leopard$elseif[$splitText[2]==Yeti]<:Yeti:$var[id39]> Yeti$elseif[$splitText[2]==Kitsune]<:Kitsune:$var[id40]> Kitsune$elseif[$splitText[2]==Dragon]<:EasternDragon:$var[id41]> Dragon$endif]
$var[fruit3;$if[$splitText[3]==Rocket]<:Rocket:$var[id1]> Rocket$elseif[$splitText[3]==Spin]<:Spin:$var[id2]> Spin$elseif[$splitText[3]==Blade]<:Blade:$var[id3]> Blade$elseif[$splitText[3]==Spring]<:Spring:$var[id4]> Spring$elseif[$splitText[3]==Bomb]<:Bomb:$var[id5]> Bomb$elseif[$splitText[3]==Smoke]<:Smoke:$var[id6]> Smoke$elseif[$splitText[3]==Spike]<:Spike:$var[id7]> Spike$elseif[$splitText[3]==Flame]<:Flame:$var[id8]> Flame$elseif[$splitText[3]==Ice]<:Ice:$var[id9]> Ice$elseif[$splitText[3]==Sand]<:Sand:$var[id10]> Sand$elseif[$splitText[3]==Dark]<:Dark:$var[id11]> Dark$elseif[$splitText[3]==Eagle]<:Eagle:$var[id12]> Eagle$elseif[$splitText[3]==Diamond]<:Diamond:$var[id13]> Diamond$elseif[$splitText[3]==Light]<:Light:$var[id14]> Light$elseif[$splitText[3]==Rubber]<:Rubber:$var[id15]> Rubber$elseif[$splitText[3]==Ghost]<:Ghost:$var[id16]> Ghost$elseif[$splitText[3]==Magma]<:Magma:$var[id17]> Magma$elseif[$splitText[3]==Quake]<:Quake:$var[id18]> Quake$elseif[$splitText[3]==Buddha]<:Buddha:$var[id19]> Buddha$elseif[$splitText[3]==Love]<:Love:$var[id20]> Love$elseif[$splitText[3]==Creation]<:Creation:$var[id21]> Creation$elseif[$splitText[3]==Spider]<:Spider:$var[id22]> Spider$elseif[$splitText[3]==Sound]<:Sound:$var[id23]> Sound$elseif[$splitText[3]==Phoenix]<:Phoenix:$var[id24]> Phoenix$elseif[$splitText[3]==Portal]<:Portal:$var[id25]> Portal$elseif[$splitText[3]==Rumble]<:Rumble:$var[id26]> Rumble$elseif[$splitText[3]==Pain]<:Pain:$var[id27]> Pain$elseif[$splitText[3]==Blizzard]<:Blizzard:$var[id28]> Blizzard$elseif[$splitText[3]==Gravity]<:Gravity:$var[id29]> Gravity$elseif[$splitText[3]==Mammoth]<:Mammoth:$var[id30]> Mammoth$elseif[$splitText[3]==T-Rex]<:TRex:$var[id31]> T-Rex$elseif[$splitText[3]==Dough]<:Dough:$var[id32]> Dough$elseif[$splitText[3]==Shadow]<:Shadow:$var[id33]> Shadow$elseif[$splitText[3]==Venom]<:Venom:$var[id34]> Venom$elseif[$splitText[3]==Control]<:Control:$var[id35]> Control$elseif[$splitText[3]==Gas]<:Gas:$var[id36]> Gas$elseif[$splitText[3]==Spirit]<:Spirit:$var[id37]> Spirit$elseif[$splitText[3]==Leopard]<:Leopard:$var[id38]> Leopard$elseif[$splitText[3]==Yeti]<:Yeti:$var[id39]> Yeti$elseif[$splitText[3]==Kitsune]<:Kitsune:$var[id40]> Kitsune$elseif[$splitText[3]==Dragon]<:EasternDragon:$var[id41]> Dragon$endif]
$var[fruit4;$if[$splitText[4]==Rocket]<:Rocket:$var[id1]> Rocket$elseif[$splitText[4]==Spin]<:Spin:$var[id2]> Spin$elseif[$splitText[4]==Blade]<:Blade:$var[id3]> Blade$elseif[$splitText[4]==Spring]<:Spring:$var[id4]> Spring$elseif[$splitText[4]==Bomb]<:Bomb:$var[id5]> Bomb$elseif[$splitText[4]==Smoke]<:Smoke:$var[id6]> Smoke$elseif[$splitText[4]==Spike]<:Spike:$var[id7]> Spike$elseif[$splitText[4]==Flame]<:Flame:$var[id8]> Flame$elseif[$splitText[4]==Ice]<:Ice:$var[id9]> Ice$elseif[$splitText[4]==Sand]<:Sand:$var[id10]> Sand$elseif[$splitText[4]==Dark]<:Dark:$var[id11]> Dark$elseif[$splitText[4]==Eagle]<:Eagle:$var[id12]> Eagle$elseif[$splitText[4]==Diamond]<:Diamond:$var[id13]> Diamond$elseif[$splitText[4]==Light]<:Light:$var[id14]> Light$elseif[$splitText[4]==Rubber]<:Rubber:$var[id15]> Rubber$elseif[$splitText[4]==Ghost]<:Ghost:$var[id16]> Ghost$elseif[$splitText[4]==Magma]<:Magma:$var[id17]> Magma$elseif[$splitText[4]==Quake]<:Quake:$var[id18]> Quake$elseif[$splitText[4]==Buddha]<:Buddha:$var[id19]> Buddha$elseif[$splitText[4]==Love]<:Love:$var[id20]> Love$elseif[$splitText[4]==Creation]<:Creation:$var[id21]> Creation$elseif[$splitText[4]==Spider]<:Spider:$var[id22]> Spider$elseif[$splitText[4]==Sound]<:Sound:$var[id23]> Sound$elseif[$splitText[4]==Phoenix]<:Phoenix:$var[id24]> Phoenix$elseif[$splitText[4]==Portal]<:Portal:$var[id25]> Portal$elseif[$splitText[4]==Rumble]<:Rumble:$var[id26]> Rumble$elseif[$splitText[4]==Pain]<:Pain:$var[id27]> Pain$elseif[$splitText[4]==Blizzard]<:Blizzard:$var[id28]> Blizzard$elseif[$splitText[4]==Gravity]<:Gravity:$var[id29]> Gravity$elseif[$splitText[4]==Mammoth]<:Mammoth:$var[id30]> Mammoth$elseif[$splitText[4]==T-Rex]<:TRex:$var[id31]> T-Rex$elseif[$splitText[4]==Dough]<:Dough:$var[id32]> Dough$elseif[$splitText[4]==Shadow]<:Shadow:$var[id33]> Shadow$elseif[$splitText[4]==Venom]<:Venom:$var[id34]> Venom$elseif[$splitText[4]==Control]<:Control:$var[id35]> Control$elseif[$splitText[4]==Gas]<:Gas:$var[id36]> Gas$elseif[$splitText[4]==Spirit]<:Spirit:$var[id37]> Spirit$elseif[$splitText[4]==Leopard]<:Leopard:$var[id38]> Leopard$elseif[$splitText[4]==Yeti]<:Yeti:$var[id39]> Yeti$elseif[$splitText[4]==Kitsune]<:Kitsune:$var[id40]> Kitsune$elseif[$splitText[4]==Dragon]<:EasternDragon:$var[id41]> Dragon$endif]
$var[fruit5;$if[$splitText[5]==Rocket]<:Rocket:$var[id1]> Rocket$elseif[$splitText[5]==Spin]<:Spin:$var[id2]> Spin$elseif[$splitText[5]==Blade]<:Blade:$var[id3]> Blade$elseif[$splitText[5]==Spring]<:Spring:$var[id4]> Spring$elseif[$splitText[5]==Bomb]<:Bomb:$var[id5]> Bomb$elseif[$splitText[5]==Smoke]<:Smoke:$var[id6]> Smoke$elseif[$splitText[5]==Spike]<:Spike:$var[id7]> Spike$elseif[$splitText[5]==Flame]<:Flame:$var[id8]> Flame$elseif[$splitText[5]==Ice]<:Ice:$var[id9]> Ice$elseif[$splitText[5]==Sand]<:Sand:$var[id10]> Sand$elseif[$splitText[5]==Dark]<:Dark:$var[id11]> Dark$elseif[$splitText[5]==Eagle]<:Eagle:$var[id12]> Eagle$elseif[$splitText[5]==Diamond]<:Diamond:$var[id13]> Diamond$elseif[$splitText[5]==Light]<:Light:$var[id14]> Light$elseif[$splitText[5]==Rubber]<:Rubber:$var[id15]> Rubber$elseif[$splitText[5]==Ghost]<:Ghost:$var[id16]> Ghost$elseif[$splitText[5]==Magma]<:Magma:$var[id17]> Magma$elseif[$splitText[5]==Quake]<:Quake:$var[id18]> Quake$elseif[$splitText[5]==Buddha]<:Buddha:$var[id19]> Buddha$elseif[$splitText[5]==Love]<:Love:$var[id20]> Love$elseif[$splitText[5]==Creation]<:Creation:$var[id21]> Creation$elseif[$splitText[5]==Spider]<:Spider:$var[id22]> Spider$elseif[$splitText[5]==Sound]<:Sound:$var[id23]> Sound$elseif[$splitText[5]==Phoenix]<:Phoenix:$var[id24]> Phoenix$elseif[$splitText[5]==Portal]<:Portal:$var[id25]> Portal$elseif[$splitText[5]==Rumble]<:Rumble:$var[id26]> Rumble$elseif[$splitText[5]==Pain]<:Pain:$var[id27]> Pain$elseif[$splitText[5]==Blizzard]<:Blizzard:$var[id28]> Blizzard$elseif[$splitText[5]==Gravity]<:Gravity:$var[id29]> Gravity$elseif[$splitText[5]==Mammoth]<:Mammoth:$var[id30]> Mammoth$elseif[$splitText[5]==T-Rex]<:TRex:$var[id31]> T-Rex$elseif[$splitText[5]==Dough]<:Dough:$var[id32]> Dough$elseif[$splitText[5]==Shadow]<:Shadow:$var[id33]> Shadow$elseif[$splitText[5]==Venom]<:Venom:$var[id34]> Venom$elseif[$splitText[5]==Control]<:Control:$var[id35]> Control$elseif[$splitText[5]==Gas]<:Gas:$var[id36]> Gas$elseif[$splitText[5]==Spirit]<:Spirit:$var[id37]> Spirit$elseif[$splitText[5]==Leopard]<:Leopard:$var[id38]> Leopard$elseif[$splitText[5]==Yeti]<:Yeti:$var[id39]> Yeti$elseif[$splitText[5]==Kitsune]<:Kitsune:$var[id40]> Kitsune$elseif[$splitText[5]==Dragon]<:EasternDragon:$var[id41]> Dragon$endif]
$var[fruit6;$if[$splitText[6]==Rocket]<:Rocket:$var[id1]> Rocket$elseif[$splitText[6]==Spin]<:Spin:$var[id2]> Spin$elseif[$splitText[6]==Blade]<:Blade:$var[id3]> Blade$elseif[$splitText[6]==Spring]<:Spring:$var[id4]> Spring$elseif[$splitText[6]==Bomb]<:Bomb:$var[id5]> Bomb$elseif[$splitText[6]==Smoke]<:Smoke:$var[id6]> Smoke$elseif[$splitText[6]==Spike]<:Spike:$var[id7]> Spike$elseif[$splitText[6]==Flame]<:Flame:$var[id8]> Flame$elseif[$splitText[6]==Ice]<:Ice:$var[id9]> Ice$elseif[$splitText[6]==Sand]<:Sand:$var[id10]> Sand$elseif[$splitText[6]==Dark]<:Dark:$var[id11]> Dark$elseif[$splitText[6]==Eagle]<:Eagle:$var[id12]> Eagle$elseif[$splitText[6]==Diamond]<:Diamond:$var[id13]> Diamond$elseif[$splitText[6]==Light]<:Light:$var[id14]> Light$elseif[$splitText[6]==Rubber]<:Rubber:$var[id15]> Rubber$elseif[$splitText[6]==Ghost]<:Ghost:$var[id16]> Ghost$elseif[$splitText[6]==Magma]<:Magma:$var[id17]> Magma$elseif[$splitText[6]==Quake]<:Quake:$var[id18]> Quake$elseif[$splitText[6]==Buddha]<:Buddha:$var[id19]> Buddha$elseif[$splitText[6]==Love]<:Love:$var[id20]> Love$elseif[$splitText[6]==Creation]<:Creation:$var[id21]> Creation$elseif[$splitText[6]==Spider]<:Spider:$var[id22]> Spider$elseif[$splitText[6]==Sound]<:Sound:$var[id23]> Sound$elseif[$splitText[6]==Phoenix]<:Phoenix:$var[id24]> Phoenix$elseif[$splitText[6]==Portal]<:Portal:$var[id25]> Portal$elseif[$splitText[6]==Rumble]<:Rumble:$var[id26]> Rumble$elseif[$splitText[6]==Pain]<:Pain:$var[id27]> Pain$elseif[$splitText[6]==Blizzard]<:Blizzard:$var[id28]> Blizzard$elseif[$splitText[6]==Gravity]<:Gravity:$var[id29]> Gravity$elseif[$splitText[6]==Mammoth]<:Mammoth:$var[id30]> Mammoth$elseif[$splitText[6]==T-Rex]<:TRex:$var[id31]> T-Rex$elseif[$splitText[6]==Dough]<:Dough:$var[id32]> Dough$elseif[$splitText[6]==Shadow]<:Shadow:$var[id33]> Shadow$elseif[$splitText[6]==Venom]<:Venom:$var[id34]> Venom$elseif[$splitText[6]==Control]<:Control:$var[id35]> Control$elseif[$splitText[6]==Gas]<:Gas:$var[id36]> Gas$elseif[$splitText[6]==Spirit]<:Spirit:$var[id37]> Spirit$elseif[$splitText[6]==Leopard]<:Leopard:$var[id38]> Leopard$elseif[$splitText[6]==Yeti]<:Yeti:$var[id39]> Yeti$elseif[$splitText[6]==Kitsune]<:Kitsune:$var[id40]> Kitsune$elseif[$splitText[6]==Dragon]<:EasternDragon:$var[id41]> Dragon$endif]
$var[fruit7;$if[$splitText[7]==Rocket]<:Rocket:$var[id1]> Rocket$elseif[$splitText[7]==Spin]<:Spin:$var[id2]> Spin$elseif[$splitText[7]==Blade]<:Blade:$var[id3]> Blade$elseif[$splitText[7]==Spring]<:Spring:$var[id4]> Spring$elseif[$splitText[7]==Bomb]<:Bomb:$var[id5]> Bomb$elseif[$splitText[7]==Smoke]<:Smoke:$var[id6]> Smoke$elseif[$splitText[7]==Spike]<:Spike:$var[id7]> Spike$elseif[$splitText[7]==Flame]<:Flame:$var[id8]> Flame$elseif[$splitText[7]==Ice]<:Ice:$var[id9]> Ice$elseif[$splitText[7]==Sand]<:Sand:$var[id10]> Sand$elseif[$splitText[7]==Dark]<:Dark:$var[id11]> Dark$elseif[$splitText[7]==Eagle]<:Eagle:$var[id12]> Eagle$elseif[$splitText[7]==Diamond]<:Diamond:$var[id13]> Diamond$elseif[$splitText[7]==Light]<:Light:$var[id14]> Light$elseif[$splitText[7]==Rubber]<:Rubber:$var[id15]> Rubber$elseif[$splitText[7]==Ghost]<:Ghost:$var[id16]> Ghost$elseif[$splitText[7]==Magma]<:Magma:$var[id17]> Magma$elseif[$splitText[7]==Quake]<:Quake:$var[id18]> Quake$elseif[$splitText[7]==Buddha]<:Buddha:$var[id19]> Buddha$elseif[$splitText[7]==Love]<:Love:$var[id20]> Love$elseif[$splitText[7]==Creation]<:Creation:$var[id21]> Creation$elseif[$splitText[7]==Spider]<:Spider:$var[id22]> Spider$elseif[$splitText[7]==Sound]<:Sound:$var[id23]> Sound$elseif[$splitText[7]==Phoenix]<:Phoenix:$var[id24]> Phoenix$elseif[$splitText[7]==Portal]<:Portal:$var[id25]> Portal$elseif[$splitText[7]==Rumble]<:Rumble:$var[id26]> Rumble$elseif[$splitText[7]==Pain]<:Pain:$var[id27]> Pain$elseif[$splitText[7]==Blizzard]<:Blizzard:$var[id28]> Blizzard$elseif[$splitText[7]==Gravity]<:Gravity:$var[id29]> Gravity$elseif[$splitText[7]==Mammoth]<:Mammoth:$var[id30]> Mammoth$elseif[$splitText[7]==T-Rex]<:TRex:$var[id31]> T-Rex$elseif[$splitText[7]==Dough]<:Dough:$var[id32]> Dough$elseif[$splitText[7]==Shadow]<:Shadow:$var[id33]> Shadow$elseif[$splitText[7]==Venom]<:Venom:$var[id34]> Venom$elseif[$splitText[7]==Control]<:Control:$var[id35]> Control$elseif[$splitText[7]==Gas]<:Gas:$var[id36]> Gas$elseif[$splitText[7]==Spirit]<:Spirit:$var[id37]> Spirit$elseif[$splitText[7]==Leopard]<:Leopard:$var[id38]> Leopard$elseif[$splitText[7]==Yeti]<:Yeti:$var[id39]> Yeti$elseif[$splitText[7]==Kitsune]<:Kitsune:$var[id40]> Kitsune$elseif[$splitText[7]==Dragon]<:EasternDragon:$var[id41]> Dragon$endif]
$var[fruit8;$if[$splitText[8]==Rocket]<:Rocket:$var[id1]> Rocket$elseif[$splitText[8]==Spin]<:Spin:$var[id2]> Spin$elseif[$splitText[8]==Blade]<:Blade:$var[id3]> Blade$elseif[$splitText[8]==Spring]<:Spring:$var[id4]> Spring$elseif[$splitText[8]==Bomb]<:Bomb:$var[id5]> Bomb$elseif[$splitText[8]==Smoke]<:Smoke:$var[id6]> Smoke$elseif[$splitText[8]==Spike]<:Spike:$var[id7]> Spike$elseif[$splitText[8]==Flame]<:Flame:$var[id8]> Flame$elseif[$splitText[8]==Ice]<:Ice:$var[id9]> Ice$elseif[$splitText[8]==Sand]<:Sand:$var[id10]> Sand$elseif[$splitText[8]==Dark]<:Dark:$var[id11]> Dark$elseif[$splitText[8]==Eagle]<:Eagle:$var[id12]> Eagle$elseif[$splitText[8]==Diamond]<:Diamond:$var[id13]> Diamond$elseif[$splitText[8]==Light]<:Light:$var[id14]> Light$elseif[$splitText[8]==Rubber]<:Rubber:$var[id15]> Rubber$elseif[$splitText[8]==Ghost]<:Ghost:$var[id16]> Ghost$elseif[$splitText[8]==Magma]<:Magma:$var[id17]> Magma$elseif[$splitText[8]==Quake]<:Quake:$var[id18]> Quake$elseif[$splitText[8]==Buddha]<:Buddha:$var[id19]> Buddha$elseif[$splitText[8]==Love]<:Love:$var[id20]> Love$elseif[$splitText[8]==Creation]<:Creation:$var[id21]> Creation$elseif[$splitText[8]==Spider]<:Spider:$var[id22]> Spider$elseif[$splitText[8]==Sound]<:Sound:$var[id23]> Sound$elseif[$splitText[8]==Phoenix]<:Phoenix:$var[id24]> Phoenix$elseif[$splitText[8]==Portal]<:Portal:$var[id25]> Portal$elseif[$splitText[8]==Rumble]<:Rumble:$var[id26]> Rumble$elseif[$splitText[8]==Pain]<:Pain:$var[id27]> Pain$elseif[$splitText[8]==Blizzard]<:Blizzard:$var[id28]> Blizzard$elseif[$splitText[8]==Gravity]<:Gravity:$var[id29]> Gravity$elseif[$splitText[8]==Mammoth]<:Mammoth:$var[id30]> Mammoth$elseif[$splitText[8]==T-Rex]<:TRex:$var[id31]> T-Rex$elseif[$splitText[8]==Dough]<:Dough:$var[id32]> Dough$elseif[$splitText[8]==Shadow]<:Shadow:$var[id33]> Shadow$elseif[$splitText[8]==Venom]<:Venom:$var[id34]> Venom$elseif[$splitText[8]==Control]<:Control:$var[id35]> Control$elseif[$splitText[8]==Gas]<:Gas:$var[id36]> Gas$elseif[$splitText[8]==Spirit]<:Spirit:$var[id37]> Spirit$elseif[$splitText[8]==Leopard]<:Leopard:$var[id38]> Leopard$elseif[$splitText[8]==Yeti]<:Yeti:$var[id39]> Yeti$elseif[$splitText[8]==Kitsune]<:Kitsune:$var[id40]> Kitsune$elseif[$splitText[8]==Dragon]<:EasternDragon:$var[id41]> Dragon$endif]
$var[fruit9;$if[$splitText[9]==Rocket]<:Rocket:$var[id1]> Rocket$elseif[$splitText[9]==Spin]<:Spin:$var[id2]> Spin$elseif[$splitText[9]==Blade]<:Blade:$var[id3]> Blade$elseif[$splitText[9]==Spring]<:Spring:$var[id4]> Spring$elseif[$splitText[9]==Bomb]<:Bomb:$var[id5]> Bomb$elseif[$splitText[9]==Smoke]<:Smoke:$var[id6]> Smoke$elseif[$splitText[9]==Spike]<:Spike:$var[id7]> Spike$elseif[$splitText[9]==Flame]<:Flame:$var[id8]> Flame$elseif[$splitText[9]==Ice]<:Ice:$var[id9]> Ice$elseif[$splitText[9]==Sand]<:Sand:$var[id10]> Sand$elseif[$splitText[9]==Dark]<:Dark:$var[id11]> Dark$elseif[$splitText[9]==Eagle]<:Eagle:$var[id12]> Eagle$elseif[$splitText[9]==Diamond]<:Diamond:$var[id13]> Diamond$elseif[$splitText[9]==Light]<:Light:$var[id14]> Light$elseif[$splitText[9]==Rubber]<:Rubber:$var[id15]> Rubber$elseif[$splitText[9]==Ghost]<:Ghost:$var[id16]> Ghost$elseif[$splitText[9]==Magma]<:Magma:$var[id17]> Magma$elseif[$splitText[9]==Quake]<:Quake:$var[id18]> Quake$elseif[$splitText[9]==Buddha]<:Buddha:$var[id19]> Buddha$elseif[$splitText[9]==Love]<:Love:$var[id20]> Love$elseif[$splitText[9]==Creation]<:Creation:$var[id21]> Creation$elseif[$splitText[9]==Spider]<:Spider:$var[id22]> Spider$elseif[$splitText[9]==Sound]<:Sound:$var[id23]> Sound$elseif[$splitText[9]==Phoenix]<:Phoenix:$var[id24]> Phoenix$elseif[$splitText[9]==Portal]<:Portal:$var[id25]> Portal$elseif[$splitText[9]==Rumble]<:Rumble:$var[id26]> Rumble$elseif[$splitText[9]==Pain]<:Pain:$var[id27]> Pain$elseif[$splitText[9]==Blizzard]<:Blizzard:$var[id28]> Blizzard$elseif[$splitText[9]==Gravity]<:Gravity:$var[id29]> Gravity$elseif[$splitText[9]==Mammoth]<:Mammoth:$var[id30]> Mammoth$elseif[$splitText[9]==T-Rex]<:TRex:$var[id31]> T-Rex$elseif[$splitText[9]==Dough]<:Dough:$var[id32]> Dough$elseif[$splitText[9]==Shadow]<:Shadow:$var[id33]> Shadow$elseif[$splitText[9]==Venom]<:Venom:$var[id34]> Venom$elseif[$splitText[9]==Control]<:Control:$var[id35]> Control$elseif[$splitText[9]==Gas]<:Gas:$var[id36]> Gas$elseif[$splitText[9]==Spirit]<:Spirit:$var[id37]> Spirit$elseif[$splitText[9]==Leopard]<:Leopard:$var[id38]> Leopard$elseif[$splitText[9]==Yeti]<:Yeti:$var[id39]> Yeti$elseif[$splitText[9]==Kitsune]<:Kitsune:$var[id40]> Kitsune$elseif[$splitText[9]==Dragon]<:EasternDragon:$var[id41]> Dragon$endif]
$var[fruit10;$if[$splitText[10]==Rocket]<:Rocket:$var[id1]> Rocket$elseif[$splitText[10]==Spin]<:Spin:$var[id2]> Spin$elseif[$splitText[10]==Blade]<:Blade:$var[id3]> Blade$elseif[$splitText[10]==Spring]<:Spring:$var[id4]> Spring$elseif[$splitText[10]==Bomb]<:Bomb:$var[id5]> Bomb$elseif[$splitText[10]==Smoke]<:Smoke:$var[id6]> Smoke$elseif[$splitText[10]==Spike]<:Spike:$var[id7]> Spike$elseif[$splitText[10]==Flame]<:Flame:$var[id8]> Flame$elseif[$splitText[10]==Ice]<:Ice:$var[id9]> Ice$elseif[$splitText[10]==Sand]<:Sand:$var[id10]> Sand$elseif[$splitText[10]==Dark]<:Dark:$var[id11]> Dark$elseif[$splitText[10]==Eagle]<:Eagle:$var[id12]> Eagle$elseif[$splitText[10]==Diamond]<:Diamond:$var[id13]> Diamond$elseif[$splitText[10]==Light]<:Light:$var[id14]> Light$elseif[$splitText[10]==Rubber]<:Rubber:$var[id15]> Rubber$elseif[$splitText[10]==Ghost]<:Ghost:$var[id16]> Ghost$elseif[$splitText[10]==Magma]<:Magma:$var[id17]> Magma$elseif[$splitText[10]==Quake]<:Quake:$var[id18]> Quake$elseif[$splitText[10]==Buddha]<:Buddha:$var[id19]> Buddha$elseif[$splitText[10]==Love]<:Love:$var[id20]> Love$elseif[$splitText[10]==Creation]<:Creation:$var[id21]> Creation$elseif[$splitText[10]==Spider]<:Spider:$var[id22]> Spider$elseif[$splitText[10]==Sound]<:Sound:$var[id23]> Sound$elseif[$splitText[10]==Phoenix]<:Phoenix:$var[id24]> Phoenix$elseif[$splitText[10]==Portal]<:Portal:$var[id25]> Portal$elseif[$splitText[10]==Rumble]<:Rumble:$var[id26]> Rumble$elseif[$splitText[10]==Pain]<:Pain:$var[id27]> Pain$elseif[$splitText[10]==Blizzard]<:Blizzard:$var[id28]> Blizzard$elseif[$splitText[10]==Gravity]<:Gravity:$var[id29]> Gravity$elseif[$splitText[10]==Mammoth]<:Mammoth:$var[id30]> Mammoth$elseif[$splitText[10]==T-Rex]<:TRex:$var[id31]> T-Rex$elseif[$splitText[10]==Dough]<:Dough:$var[id32]> Dough$elseif[$splitText[10]==Shadow]<:Shadow:$var[id33]> Shadow$elseif[$splitText[10]==Venom]<:Venom:$var[id34]> Venom$elseif[$splitText[10]==Control]<:Control:$var[id35]> Control$elseif[$splitText[10]==Gas]<:Gas:$var[id36]> Gas$elseif[$splitText[10]==Spirit]<:Spirit:$var[id37]> Spirit$elseif[$splitText[10]==Leopard]<:Leopard:$var[id38]> Leopard$elseif[$splitText[10]==Yeti]<:Yeti:$var[id39]> Yeti$elseif[$splitText[10]==Kitsune]<:Kitsune:$var[id40]> Kitsune$elseif[$splitText[10]==Dragon]<:EasternDragon:$var[id41]> Dragon$endif]

$title[Blox Fruits __Normal__ Stock]
$description[The Fruits are listed below:
$var[fruit1]
$var[fruit2]
$var[fruit3]
$var[fruit4]
$var[fruit5]
$var[fruit6]
$var[fruit7]
$var[fruit8]
$var[fruit9]
$var[fruit10]
]
$footer[Bloxfruits Stock | By Zubariel]

$elseif[$toLowercase[$message]==mirage]
$var[a;$replaceText[$httpResult[mirageStock];[;]]
$var[b;$replaceText[$var[a];";]]
$var[c;$replaceText[$var[b];\\];]]
$textSplit[$var[c];,]

$var[fruit1;$if[$splitText[1]==Rocket]<:Rocket:$var[id1]> Rocket$elseif[$splitText[1]==Spin]<:Spin:$var[id2]> Spin$elseif[$splitText[1]==Blade]<:Blade:$var[id3]> Blade$elseif[$splitText[1]==Spring]<:Spring:$var[id4]> Spring$elseif[$splitText[1]==Bomb]<:Bomb:$var[id5]> Bomb$elseif[$splitText[1]==Smoke]<:Smoke:$var[id6]> Smoke$elseif[$splitText[1]==Spike]<:Spike:$var[id7]> Spike$elseif[$splitText[1]==Flame]<:Flame:$var[id8]> Flame$elseif[$splitText[1]==Ice]<:Ice:$var[id9]> Ice$elseif[$splitText[1]==Sand]<:Sand:$var[id10]> Sand$elseif[$splitText[1]==Dark]<:Dark:$var[id11]> Dark$elseif[$splitText[1]==Eagle]<:Eagle:$var[id12]> Eagle$elseif[$splitText[1]==Diamond]<:Diamond:$var[id13]> Diamond$elseif[$splitText[1]==Light]<:Light:$var[id14]> Light$elseif[$splitText[1]==Rubber]<:Rubber:$var[id15]> Rubber$elseif[$splitText[1]==Ghost]<:Ghost:$var[id16]> Ghost$elseif[$splitText[1]==Magma]<:Magma:$var[id17]> Magma$elseif[$splitText[1]==Quake]<:Quake:$var[id18]> Quake$elseif[$splitText[1]==Buddha]<:Buddha:$var[id19]> Buddha$elseif[$splitText[1]==Love]<:Love:$var[id20]> Love$elseif[$splitText[1]==Creation]<:Creation:$var[id21]> Creation$elseif[$splitText[1]==Spider]<:Spider:$var[id22]> Spider$elseif[$splitText[1]==Sound]<:Sound:$var[id23]> Sound$elseif[$splitText[1]==Phoenix]<:Phoenix:$var[id24]> Phoenix$elseif[$splitText[1]==Portal]<:Portal:$var[id25]> Portal$elseif[$splitText[1]==Rumble]<:Rumble:$var[id26]> Rumble$elseif[$splitText[1]==Pain]<:Pain:$var[id27]> Pain$elseif[$splitText[1]==Blizzard]<:Blizzard:$var[id28]> Blizzard$elseif[$splitText[1]==Gravity]<:Gravity:$var[id29]> Gravity$elseif[$splitText[1]==Mammoth]<:Mammoth:$var[id30]> Mammoth$elseif[$splitText[1]==T-Rex]<:TRex:$var[id31]> T-Rex$elseif[$splitText[1]==Dough]<:Dough:$var[id32]> Dough$elseif[$splitText[1]==Shadow]<:Shadow:$var[id33]> Shadow$elseif[$splitText[1]==Venom]<:Venom:$var[id34]> Venom$elseif[$splitText[1]==Control]<:Control:$var[id35]> Control$elseif[$splitText[1]==Gas]<:Gas:$var[id36]> Gas$elseif[$splitText[1]==Spirit]<:Spirit:$var[id37]> Spirit$elseif[$splitText[1]==Leopard]<:Leopard:$var[id38]> Leopard$elseif[$splitText[1]==Yeti]<:Yeti:$var[id39]> Yeti$elseif[$splitText[1]==Kitsune]<:Kitsune:$var[id40]> Kitsune$elseif[$splitText[1]==Dragon]<:EasternDragon:$var[id41]> Dragon$endif]
$var[fruit2;$if[$splitText[2]==Rocket]<:Rocket:$var[id1]> Rocket$elseif[$splitText[2]==Spin]<:Spin:$var[id2]> Spin$elseif[$splitText[2]==Blade]<:Blade:$var[id3]> Blade$elseif[$splitText[2]==Spring]<:Spring:$var[id4]> Spring$elseif[$splitText[2]==Bomb]<:Bomb:$var[id5]> Bomb$elseif[$splitText[2]==Smoke]<:Smoke:$var[id6]> Smoke$elseif[$splitText[2]==Spike]<:Spike:$var[id7]> Spike$elseif[$splitText[2]==Flame]<:Flame:$var[id8]> Flame$elseif[$splitText[2]==Ice]<:Ice:$var[id9]> Ice$elseif[$splitText[2]==Sand]<:Sand:$var[id10]> Sand$elseif[$splitText[2]==Dark]<:Dark:$var[id11]> Dark$elseif[$splitText[2]==Eagle]<:Eagle:$var[id12]> Eagle$elseif[$splitText[2]==Diamond]<:Diamond:$var[id13]> Diamond$elseif[$splitText[2]==Light]<:Light:$var[id14]> Light$elseif[$splitText[2]==Rubber]<:Rubber:$var[id15]> Rubber$elseif[$splitText[2]==Ghost]<:Ghost:$var[id16]> Ghost$elseif[$splitText[2]==Magma]<:Magma:$var[id17]> Magma$elseif[$splitText[2]==Quake]<:Quake:$var[id18]> Quake$elseif[$splitText[2]==Buddha]<:Buddha:$var[id19]> Buddha$elseif[$splitText[2]==Love]<:Love:$var[id20]> Love$elseif[$splitText[2]==Creation]<:Creation:$var[id21]> Creation$elseif[$splitText[2]==Spider]<:Spider:$var[id22]> Spider$elseif[$splitText[2]==Sound]<:Sound:$var[id23]> Sound$elseif[$splitText[2]==Phoenix]<:Phoenix:$var[id24]> Phoenix$elseif[$splitText[2]==Portal]<:Portal:$var[id25]> Portal$elseif[$splitText[2]==Rumble]<:Rumble:$var[id26]> Rumble$elseif[$splitText[2]==Pain]<:Pain:$var[id27]> Pain$elseif[$splitText[2]==Blizzard]<:Blizzard:$var[id28]> Blizzard$elseif[$splitText[2]==Gravity]<:Gravity:$var[id29]> Gravity$elseif[$splitText[2]==Mammoth]<:Mammoth:$var[id30]> Mammoth$elseif[$splitText[2]==T-Rex]<:TRex:$var[id31]> T-Rex$elseif[$splitText[2]==Dough]<:Dough:$var[id32]> Dough$elseif[$splitText[2]==Shadow]<:Shadow:$var[id33]> Shadow$elseif[$splitText[2]==Venom]<:Venom:$var[id34]> Venom$elseif[$splitText[2]==Control]<:Control:$var[id35]> Control$elseif[$splitText[2]==Gas]<:Gas:$var[id36]> Gas$elseif[$splitText[2]==Spirit]<:Spirit:$var[id37]> Spirit$elseif[$splitText[2]==Leopard]<:Leopard:$var[id38]> Leopard$elseif[$splitText[2]==Yeti]<:Yeti:$var[id39]> Yeti$elseif[$splitText[2]==Kitsune]<:Kitsune:$var[id40]> Kitsune$elseif[$splitText[2]==Dragon]<:EasternDragon:$var[id41]> Dragon$endif]
$var[fruit3;$if[$splitText[3]==Rocket]<:Rocket:$var[id1]> Rocket$elseif[$splitText[3]==Spin]<:Spin:$var[id2]> Spin$elseif[$splitText[3]==Blade]<:Blade:$var[id3]> Blade$elseif[$splitText[3]==Spring]<:Spring:$var[id4]> Spring$elseif[$splitText[3]==Bomb]<:Bomb:$var[id5]> Bomb$elseif[$splitText[3]==Smoke]<:Smoke:$var[id6]> Smoke$elseif[$splitText[3]==Spike]<:Spike:$var[id7]> Spike$elseif[$splitText[3]==Flame]<:Flame:$var[id8]> Flame$elseif[$splitText[3]==Ice]<:Ice:$var[id9]> Ice$elseif[$splitText[3]==Sand]<:Sand:$var[id10]> Sand$elseif[$splitText[3]==Dark]<:Dark:$var[id11]> Dark$elseif[$splitText[3]==Eagle]<:Eagle:$var[id12]> Eagle$elseif[$splitText[3]==Diamond]<:Diamond:$var[id13]> Diamond$elseif[$splitText[3]==Light]<:Light:$var[id14]> Light$elseif[$splitText[3]==Rubber]<:Rubber:$var[id15]> Rubber$elseif[$splitText[3]==Ghost]<:Ghost:$var[id16]> Ghost$elseif[$splitText[3]==Magma]<:Magma:$var[id17]> Magma$elseif[$splitText[3]==Quake]<:Quake:$var[id18]> Quake$elseif[$splitText[3]==Buddha]<:Buddha:$var[id19]> Buddha$elseif[$splitText[3]==Love]<:Love:$var[id20]> Love$elseif[$splitText[3]==Creation]<:Creation:$var[id21]> Creation$elseif[$splitText[3]==Spider]<:Spider:$var[id22]> Spider$elseif[$splitText[3]==Sound]<:Sound:$var[id23]> Sound$elseif[$splitText[3]==Phoenix]<:Phoenix:$var[id24]> Phoenix$elseif[$splitText[3]==Portal]<:Portal:$var[id25]> Portal$elseif[$splitText[3]==Rumble]<:Rumble:$var[id26]> Rumble$elseif[$splitText[3]==Pain]<:Pain:$var[id27]> Pain$elseif[$splitText[3]==Blizzard]<:Blizzard:$var[id28]> Blizzard$elseif[$splitText[3]==Gravity]<:Gravity:$var[id29]> Gravity$elseif[$splitText[3]==Mammoth]<:Mammoth:$var[id30]> Mammoth$elseif[$splitText[3]==T-Rex]<:TRex:$var[id31]> T-Rex$elseif[$splitText[3]==Dough]<:Dough:$var[id32]> Dough$elseif[$splitText[3]==Shadow]<:Shadow:$var[id33]> Shadow$elseif[$splitText[3]==Venom]<:Venom:$var[id34]> Venom$elseif[$splitText[3]==Control]<:Control:$var[id35]> Control$elseif[$splitText[3]==Gas]<:Gas:$var[id36]> Gas$elseif[$splitText[3]==Spirit]<:Spirit:$var[id37]> Spirit$elseif[$splitText[3]==Leopard]<:Leopard:$var[id38]> Leopard$elseif[$splitText[3]==Yeti]<:Yeti:$var[id39]> Yeti$elseif[$splitText[3]==Kitsune]<:Kitsune:$var[id40]> Kitsune$elseif[$splitText[3]==Dragon]<:EasternDragon:$var[id41]> Dragon$endif]
$var[fruit4;$if[$splitText[4]==Rocket]<:Rocket:$var[id1]> Rocket$elseif[$splitText[4]==Spin]<:Spin:$var[id2]> Spin$elseif[$splitText[4]==Blade]<:Blade:$var[id3]> Blade$elseif[$splitText[4]==Spring]<:Spring:$var[id4]> Spring$elseif[$splitText[4]==Bomb]<:Bomb:$var[id5]> Bomb$elseif[$splitText[4]==Smoke]<:Smoke:$var[id6]> Smoke$elseif[$splitText[4]==Spike]<:Spike:$var[id7]> Spike$elseif[$splitText[4]==Flame]<:Flame:$var[id8]> Flame$elseif[$splitText[4]==Ice]<:Ice:$var[id9]> Ice$elseif[$splitText[4]==Sand]<:Sand:$var[id10]> Sand$elseif[$splitText[4]==Dark]<:Dark:$var[id11]> Dark$elseif[$splitText[4]==Eagle]<:Eagle:$var[id12]> Eagle$elseif[$splitText[4]==Diamond]<:Diamond:$var[id13]> Diamond$elseif[$splitText[4]==Light]<:Light:$var[id14]> Light$elseif[$splitText[4]==Rubber]<:Rubber:$var[id15]> Rubber$elseif[$splitText[4]==Ghost]<:Ghost:$var[id16]> Ghost$elseif[$splitText[4]==Magma]<:Magma:$var[id17]> Magma$elseif[$splitText[4]==Quake]<:Quake:$var[id18]> Quake$elseif[$splitText[4]==Buddha]<:Buddha:$var[id19]> Buddha$elseif[$splitText[4]==Love]<:Love:$var[id20]> Love$elseif[$splitText[4]==Creation]<:Creation:$var[id21]> Creation$elseif[$splitText[4]==Spider]<:Spider:$var[id22]> Spider$elseif[$splitText[4]==Sound]<:Sound:$var[id23]> Sound$elseif[$splitText[4]==Phoenix]<:Phoenix:$var[id24]> Phoenix$elseif[$splitText[4]==Portal]<:Portal:$var[id25]> Portal$elseif[$splitText[4]==Rumble]<:Rumble:$var[id26]> Rumble$elseif[$splitText[4]==Pain]<:Pain:$var[id27]> Pain$elseif[$splitText[4]==Blizzard]<:Blizzard:$var[id28]> Blizzard$elseif[$splitText[4]==Gravity]<:Gravity:$var[id29]> Gravity$elseif[$splitText[4]==Mammoth]<:Mammoth:$var[id30]> Mammoth$elseif[$splitText[4]==T-Rex]<:TRex:$var[id31]> T-Rex$elseif[$splitText[4]==Dough]<:Dough:$var[id32]> Dough$elseif[$splitText[4]==Shadow]<:Shadow:$var[id33]> Shadow$elseif[$splitText[4]==Venom]<:Venom:$var[id34]> Venom$elseif[$splitText[4]==Control]<:Control:$var[id35]> Control$elseif[$splitText[4]==Gas]<:Gas:$var[id36]> Gas$elseif[$splitText[4]==Spirit]<:Spirit:$var[id37]> Spirit$elseif[$splitText[4]==Leopard]<:Leopard:$var[id38]> Leopard$elseif[$splitText[4]==Yeti]<:Yeti:$var[id39]> Yeti$elseif[$splitText[4]==Kitsune]<:Kitsune:$var[id40]> Kitsune$elseif[$splitText[4]==Dragon]<:EasternDragon:$var[id41]> Dragon$endif]
$var[fruit5;$if[$splitText[5]==Rocket]<:Rocket:$var[id1]> Rocket$elseif[$splitText[5]==Spin]<:Spin:$var[id2]> Spin$elseif[$splitText[5]==Blade]<:Blade:$var[id3]> Blade$elseif[$splitText[5]==Spring]<:Spring:$var[id4]> Spring$elseif[$splitText[5]==Bomb]<:Bomb:$var[id5]> Bomb$elseif[$splitText[5]==Smoke]<:Smoke:$var[id6]> Smoke$elseif[$splitText[5]==Spike]<:Spike:$var[id7]> Spike$elseif[$splitText[5]==Flame]<:Flame:$var[id8]> Flame$elseif[$splitText[5]==Ice]<:Ice:$var[id9]> Ice$elseif[$splitText[5]==Sand]<:Sand:$var[id10]> Sand$elseif[$splitText[5]==Dark]<:Dark:$var[id11]> Dark$elseif[$splitText[5]==Eagle]<:Eagle:$var[id12]> Eagle$elseif[$splitText[5]==Diamond]<:Diamond:$var[id13]> Diamond$elseif[$splitText[5]==Light]<:Light:$var[id14]> Light$elseif[$splitText[5]==Rubber]<:Rubber:$var[id15]> Rubber$elseif[$splitText[5]==Ghost]<:Ghost:$var[id16]> Ghost$elseif[$splitText[5]==Magma]<:Magma:$var[id17]> Magma$elseif[$splitText[5]==Quake]<:Quake:$var[id18]> Quake$elseif[$splitText[5]==Buddha]<:Buddha:$var[id19]> Buddha$elseif[$splitText[5]==Love]<:Love:$var[id20]> Love$elseif[$splitText[5]==Creation]<:Creation:$var[id21]> Creation$elseif[$splitText[5]==Spider]<:Spider:$var[id22]> Spider$elseif[$splitText[5]==Sound]<:Sound:$var[id23]> Sound$elseif[$splitText[5]==Phoenix]<:Phoenix:$var[id24]> Phoenix$elseif[$splitText[5]==Portal]<:Portal:$var[id25]> Portal$elseif[$splitText[5]==Rumble]<:Rumble:$var[id26]> Rumble$elseif[$splitText[5]==Pain]<:Pain:$var[id27]> Pain$elseif[$splitText[5]==Blizzard]<:Blizzard:$var[id28]> Blizzard$elseif[$splitText[5]==Gravity]<:Gravity:$var[id29]> Gravity$elseif[$splitText[5]==Mammoth]<:Mammoth:$var[id30]> Mammoth$elseif[$splitText[5]==T-Rex]<:TRex:$var[id31]> T-Rex$elseif[$splitText[5]==Dough]<:Dough:$var[id32]> Dough$elseif[$splitText[5]==Shadow]<:Shadow:$var[id33]> Shadow$elseif[$splitText[5]==Venom]<:Venom:$var[id34]> Venom$elseif[$splitText[5]==Control]<:Control:$var[id35]> Control$elseif[$splitText[5]==Gas]<:Gas:$var[id36]> Gas$elseif[$splitText[5]==Spirit]<:Spirit:$var[id37]> Spirit$elseif[$splitText[5]==Leopard]<:Leopard:$var[id38]> Leopard$elseif[$splitText[5]==Yeti]<:Yeti:$var[id39]> Yeti$elseif[$splitText[5]==Kitsune]<:Kitsune:$var[id40]> Kitsune$elseif[$splitText[5]==Dragon]<:EasternDragon:$var[id41]> Dragon$endif]
$var[fruit6;$if[$splitText[6]==Rocket]<:Rocket:$var[id1]> Rocket$elseif[$splitText[6]==Spin]<:Spin:$var[id2]> Spin$elseif[$splitText[6]==Blade]<:Blade:$var[id3]> Blade$elseif[$splitText[6]==Spring]<:Spring:$var[id4]> Spring$elseif[$splitText[6]==Bomb]<:Bomb:$var[id5]> Bomb$elseif[$splitText[6]==Smoke]<:Smoke:$var[id6]> Smoke$elseif[$splitText[6]==Spike]<:Spike:$var[id7]> Spike$elseif[$splitText[6]==Flame]<:Flame:$var[id8]> Flame$elseif[$splitText[6]==Ice]<:Ice:$var[id9]> Ice$elseif[$splitText[6]==Sand]<:Sand:$var[id10]> Sand$elseif[$splitText[6]==Dark]<:Dark:$var[id11]> Dark$elseif[$splitText[6]==Eagle]<:Eagle:$var[id12]> Eagle$elseif[$splitText[6]==Diamond]<:Diamond:$var[id13]> Diamond$elseif[$splitText[6]==Light]<:Light:$var[id14]> Light$elseif[$splitText[6]==Rubber]<:Rubber:$var[id15]> Rubber$elseif[$splitText[6]==Ghost]<:Ghost:$var[id16]> Ghost$elseif[$splitText[6]==Magma]<:Magma:$var[id17]> Magma$elseif[$splitText[6]==Quake]<:Quake:$var[id18]> Quake$elseif[$splitText[6]==Buddha]<:Buddha:$var[id19]> Buddha$elseif[$splitText[6]==Love]<:Love:$var[id20]> Love$elseif[$splitText[6]==Creation]<:Creation:$var[id21]> Creation$elseif[$splitText[6]==Spider]<:Spider:$var[id22]> Spider$elseif[$splitText[6]==Sound]<:Sound:$var[id23]> Sound$elseif[$splitText[6]==Phoenix]<:Phoenix:$var[id24]> Phoenix$elseif[$splitText[6]==Portal]<:Portal:$var[id25]> Portal$elseif[$splitText[6]==Rumble]<:Rumble:$var[id26]> Rumble$elseif[$splitText[6]==Pain]<:Pain:$var[id27]> Pain$elseif[$splitText[6]==Blizzard]<:Blizzard:$var[id28]> Blizzard$elseif[$splitText[6]==Gravity]<:Gravity:$var[id29]> Gravity$elseif[$splitText[6]==Mammoth]<:Mammoth:$var[id30]> Mammoth$elseif[$splitText[6]==T-Rex]<:TRex:$var[id31]> T-Rex$elseif[$splitText[6]==Dough]<:Dough:$var[id32]> Dough$elseif[$splitText[6]==Shadow]<:Shadow:$var[id33]> Shadow$elseif[$splitText[6]==Venom]<:Venom:$var[id34]> Venom$elseif[$splitText[6]==Control]<:Control:$var[id35]> Control$elseif[$splitText[6]==Gas]<:Gas:$var[id36]> Gas$elseif[$splitText[6]==Spirit]<:Spirit:$var[id37]> Spirit$elseif[$splitText[6]==Leopard]<:Leopard:$var[id38]> Leopard$elseif[$splitText[6]==Yeti]<:Yeti:$var[id39]> Yeti$elseif[$splitText[6]==Kitsune]<:Kitsune:$var[id40]> Kitsune$elseif[$splitText[6]==Dragon]<:EasternDragon:$var[id41]> Dragon$endif]
$var[fruit7;$if[$splitText[7]==Rocket]<:Rocket:$var[id1]> Rocket$elseif[$splitText[7]==Spin]<:Spin:$var[id2]> Spin$elseif[$splitText[7]==Blade]<:Blade:$var[id3]> Blade$elseif[$splitText[7]==Spring]<:Spring:$var[id4]> Spring$elseif[$splitText[7]==Bomb]<:Bomb:$var[id5]> Bomb$elseif[$splitText[7]==Smoke]<:Smoke:$var[id6]> Smoke$elseif[$splitText[7]==Spike]<:Spike:$var[id7]> Spike$elseif[$splitText[7]==Flame]<:Flame:$var[id8]> Flame$elseif[$splitText[7]==Ice]<:Ice:$var[id9]> Ice$elseif[$splitText[7]==Sand]<:Sand:$var[id10]> Sand$elseif[$splitText[7]==Dark]<:Dark:$var[id11]> Dark$elseif[$splitText[7]==Eagle]<:Eagle:$var[id12]> Eagle$elseif[$splitText[7]==Diamond]<:Diamond:$var[id13]> Diamond$elseif[$splitText[7]==Light]<:Light:$var[id14]> Light$elseif[$splitText[7]==Rubber]<:Rubber:$var[id15]> Rubber$elseif[$splitText[7]==Ghost]<:Ghost:$var[id16]> Ghost$elseif[$splitText[7]==Magma]<:Magma:$var[id17]> Magma$elseif[$splitText[7]==Quake]<:Quake:$var[id18]> Quake$elseif[$splitText[7]==Buddha]<:Buddha:$var[id19]> Buddha$elseif[$splitText[7]==Love]<:Love:$var[id20]> Love$elseif[$splitText[7]==Creation]<:Creation:$var[id21]> Creation$elseif[$splitText[7]==Spider]<:Spider:$var[id22]> Spider$elseif[$splitText[7]==Sound]<:Sound:$var[id23]> Sound$elseif[$splitText[7]==Phoenix]<:Phoenix:$var[id24]> Phoenix$elseif[$splitText[7]==Portal]<:Portal:$var[id25]> Portal$elseif[$splitText[7]==Rumble]<:Rumble:$var[id26]> Rumble$elseif[$splitText[7]==Pain]<:Pain:$var[id27]> Pain$elseif[$splitText[7]==Blizzard]<:Blizzard:$var[id28]> Blizzard$elseif[$splitText[7]==Gravity]<:Gravity:$var[id29]> Gravity$elseif[$splitText[7]==Mammoth]<:Mammoth:$var[id30]> Mammoth$elseif[$splitText[7]==T-Rex]<:TRex:$var[id31]> T-Rex$elseif[$splitText[7]==Dough]<:Dough:$var[id32]> Dough$elseif[$splitText[7]==Shadow]<:Shadow:$var[id33]> Shadow$elseif[$splitText[7]==Venom]<:Venom:$var[id34]> Venom$elseif[$splitText[7]==Control]<:Control:$var[id35]> Control$elseif[$splitText[7]==Gas]<:Gas:$var[id36]> Gas$elseif[$splitText[7]==Spirit]<:Spirit:$var[id37]> Spirit$elseif[$splitText[7]==Leopard]<:Leopard:$var[id38]> Leopard$elseif[$splitText[7]==Yeti]<:Yeti:$var[id39]> Yeti$elseif[$splitText[7]==Kitsune]<:Kitsune:$var[id40]> Kitsune$elseif[$splitText[7]==Dragon]<:EasternDragon:$var[id41]> Dragon$endif]
$var[fruit8;$if[$splitText[8]==Rocket]<:Rocket:$var[id1]> Rocket$elseif[$splitText[8]==Spin]<:Spin:$var[id2]> Spin$elseif[$splitText[8]==Blade]<:Blade:$var[id3]> Blade$elseif[$splitText[8]==Spring]<:Spring:$var[id4]> Spring$elseif[$splitText[8]==Bomb]<:Bomb:$var[id5]> Bomb$elseif[$splitText[8]==Smoke]<:Smoke:$var[id6]> Smoke$elseif[$splitText[8]==Spike]<:Spike:$var[id7]> Spike$elseif[$splitText[8]==Flame]<:Flame:$var[id8]> Flame$elseif[$splitText[8]==Ice]<:Ice:$var[id9]> Ice$elseif[$splitText[8]==Sand]<:Sand:$var[id10]> Sand$elseif[$splitText[8]==Dark]<:Dark:$var[id11]> Dark$elseif[$splitText[8]==Eagle]<:Eagle:$var[id12]> Eagle$elseif[$splitText[8]==Diamond]<:Diamond:$var[id13]> Diamond$elseif[$splitText[8]==Light]<:Light:$var[id14]> Light$elseif[$splitText[8]==Rubber]<:Rubber:$var[id15]> Rubber$elseif[$splitText[8]==Ghost]<:Ghost:$var[id16]> Ghost$elseif[$splitText[8]==Magma]<:Magma:$var[id17]> Magma$elseif[$splitText[8]==Quake]<:Quake:$var[id18]> Quake$elseif[$splitText[8]==Buddha]<:Buddha:$var[id19]> Buddha$elseif[$splitText[8]==Love]<:Love:$var[id20]> Love$elseif[$splitText[8]==Creation]<:Creation:$var[id21]> Creation$elseif[$splitText[8]==Spider]<:Spider:$var[id22]> Spider$elseif[$splitText[8]==Sound]<:Sound:$var[id23]> Sound$elseif[$splitText[8]==Phoenix]<:Phoenix:$var[id24]> Phoenix$elseif[$splitText[8]==Portal]<:Portal:$var[id25]> Portal$elseif[$splitText[8]==Rumble]<:Rumble:$var[id26]> Rumble$elseif[$splitText[8]==Pain]<:Pain:$var[id27]> Pain$elseif[$splitText[8]==Blizzard]<:Blizzard:$var[id28]> Blizzard$elseif[$splitText[8]==Gravity]<:Gravity:$var[id29]> Gravity$elseif[$splitText[8]==Mammoth]<:Mammoth:$var[id30]> Mammoth$elseif[$splitText[8]==T-Rex]<:TRex:$var[id31]> T-Rex$elseif[$splitText[8]==Dough]<:Dough:$var[id32]> Dough$elseif[$splitText[8]==Shadow]<:Shadow:$var[id33]> Shadow$elseif[$splitText[8]==Venom]<:Venom:$var[id34]> Venom$elseif[$splitText[8]==Control]<:Control:$var[id35]> Control$elseif[$splitText[8]==Gas]<:Gas:$var[id36]> Gas$elseif[$splitText[8]==Spirit]<:Spirit:$var[id37]> Spirit$elseif[$splitText[8]==Leopard]<:Leopard:$var[id38]> Leopard$elseif[$splitText[8]==Yeti]<:Yeti:$var[id39]> Yeti$elseif[$splitText[8]==Kitsune]<:Kitsune:$var[id40]> Kitsune$elseif[$splitText[8]==Dragon]<:EasternDragon:$var[id41]> Dragon$endif]
$var[fruit9;$if[$splitText[9]==Rocket]<:Rocket:$var[id1]> Rocket$elseif[$splitText[9]==Spin]<:Spin:$var[id2]> Spin$elseif[$splitText[9]==Blade]<:Blade:$var[id3]> Blade$elseif[$splitText[9]==Spring]<:Spring:$var[id4]> Spring$elseif[$splitText[9]==Bomb]<:Bomb:$var[id5]> Bomb$elseif[$splitText[9]==Smoke]<:Smoke:$var[id6]> Smoke$elseif[$splitText[9]==Spike]<:Spike:$var[id7]> Spike$elseif[$splitText[9]==Flame]<:Flame:$var[id8]> Flame$elseif[$splitText[9]==Ice]<:Ice:$var[id9]> Ice$elseif[$splitText[9]==Sand]<:Sand:$var[id10]> Sand$elseif[$splitText[9]==Dark]<:Dark:$var[id11]> Dark$elseif[$splitText[9]==Eagle]<:Eagle:$var[id12]> Eagle$elseif[$splitText[9]==Diamond]<:Diamond:$var[id13]> Diamond$elseif[$splitText[9]==Light]<:Light:$var[id14]> Light$elseif[$splitText[9]==Rubber]<:Rubber:$var[id15]> Rubber$elseif[$splitText[9]==Ghost]<:Ghost:$var[id16]> Ghost$elseif[$splitText[9]==Magma]<:Magma:$var[id17]> Magma$elseif[$splitText[9]==Quake]<:Quake:$var[id18]> Quake$elseif[$splitText[9]==Buddha]<:Buddha:$var[id19]> Buddha$elseif[$splitText[9]==Love]<:Love:$var[id20]> Love$elseif[$splitText[9]==Creation]<:Creation:$var[id21]> Creation$elseif[$splitText[9]==Spider]<:Spider:$var[id22]> Spider$elseif[$splitText[9]==Sound]<:Sound:$var[id23]> Sound$elseif[$splitText[9]==Phoenix]<:Phoenix:$var[id24]> Phoenix$elseif[$splitText[9]==Portal]<:Portal:$var[id25]> Portal$elseif[$splitText[9]==Rumble]<:Rumble:$var[id26]> Rumble$elseif[$splitText[9]==Pain]<:Pain:$var[id27]> Pain$elseif[$splitText[9]==Blizzard]<:Blizzard:$var[id28]> Blizzard$elseif[$splitText[9]==Gravity]<:Gravity:$var[id29]> Gravity$elseif[$splitText[9]==Mammoth]<:Mammoth:$var[id30]> Mammoth$elseif[$splitText[9]==T-Rex]<:TRex:$var[id31]> T-Rex$elseif[$splitText[9]==Dough]<:Dough:$var[id32]> Dough$elseif[$splitText[9]==Shadow]<:Shadow:$var[id33]> Shadow$elseif[$splitText[9]==Venom]<:Venom:$var[id34]> Venom$elseif[$splitText[9]==Control]<:Control:$var[id35]> Control$elseif[$splitText[9]==Gas]<:Gas:$var[id36]> Gas$elseif[$splitText[9]==Spirit]<:Spirit:$var[id37]> Spirit$elseif[$splitText[9]==Leopard]<:Leopard:$var[id38]> Leopard$elseif[$splitText[9]==Yeti]<:Yeti:$var[id39]> Yeti$elseif[$splitText[9]==Kitsune]<:Kitsune:$var[id40]> Kitsune$elseif[$splitText[9]==Dragon]<:EasternDragon:$var[id41]> Dragon$endif]
$var[fruit10;$if[$splitText[10]==Rocket]<:Rocket:$var[id1]> Rocket$elseif[$splitText[10]==Spin]<:Spin:$var[id2]> Spin$elseif[$splitText[10]==Blade]<:Blade:$var[id3]> Blade$elseif[$splitText[10]==Spring]<:Spring:$var[id4]> Spring$elseif[$splitText[10]==Bomb]<:Bomb:$var[id5]> Bomb$elseif[$splitText[10]==Smoke]<:Smoke:$var[id6]> Smoke$elseif[$splitText[10]==Spike]<:Spike:$var[id7]> Spike$elseif[$splitText[10]==Flame]<:Flame:$var[id8]> Flame$elseif[$splitText[10]==Ice]<:Ice:$var[id9]> Ice$elseif[$splitText[10]==Sand]<:Sand:$var[id10]> Sand$elseif[$splitText[10]==Dark]<:Dark:$var[id11]> Dark$elseif[$splitText[10]==Eagle]<:Eagle:$var[id12]> Eagle$elseif[$splitText[10]==Diamond]<:Diamond:$var[id13]> Diamond$elseif[$splitText[10]==Light]<:Light:$var[id14]> Light$elseif[$splitText[10]==Rubber]<:Rubber:$var[id15]> Rubber$elseif[$splitText[10]==Ghost]<:Ghost:$var[id16]> Ghost$elseif[$splitText[10]==Magma]<:Magma:$var[id17]> Magma$elseif[$splitText[10]==Quake]<:Quake:$var[id18]> Quake$elseif[$splitText[10]==Buddha]<:Buddha:$var[id19]> Buddha$elseif[$splitText[10]==Love]<:Love:$var[id20]> Love$elseif[$splitText[10]==Creation]<:Creation:$var[id21]> Creation$elseif[$splitText[10]==Spider]<:Spider:$var[id22]> Spider$elseif[$splitText[10]==Sound]<:Sound:$var[id23]> Sound$elseif[$splitText[10]==Phoenix]<:Phoenix:$var[id24]> Phoenix$elseif[$splitText[10]==Portal]<:Portal:$var[id25]> Portal$elseif[$splitText[10]==Rumble]<:Rumble:$var[id26]> Rumble$elseif[$splitText[10]==Pain]<:Pain:$var[id27]> Pain$elseif[$splitText[10]==Blizzard]<:Blizzard:$var[id28]> Blizzard$elseif[$splitText[10]==Gravity]<:Gravity:$var[id29]> Gravity$elseif[$splitText[10]==Mammoth]<:Mammoth:$var[id30]> Mammoth$elseif[$splitText[10]==T-Rex]<:TRex:$var[id31]> T-Rex$elseif[$splitText[10]==Dough]<:Dough:$var[id32]> Dough$elseif[$splitText[10]==Shadow]<:Shadow:$var[id33]> Shadow$elseif[$splitText[10]==Venom]<:Venom:$var[id34]> Venom$elseif[$splitText[10]==Control]<:Control:$var[id35]> Control$elseif[$splitText[10]==Gas]<:Gas:$var[id36]> Gas$elseif[$splitText[10]==Spirit]<:Spirit:$var[id37]> Spirit$elseif[$splitText[10]==Leopard]<:Leopard:$var[id38]> Leopard$elseif[$splitText[10]==Yeti]<:Yeti:$var[id39]> Yeti$elseif[$splitText[10]==Kitsune]<:Kitsune:$var[id40]> Kitsune$elseif[$splitText[10]==Dragon]<:EasternDragon:$var[id41]> Dragon$endif]

$title[Blox Fruits __Mirage__ Stock]
$description[The Fruits are listed below:
$var[fruit1]
$var[fruit2]
$var[fruit3]
$var[fruit4]
$var[fruit5]
$var[fruit6]
$var[fruit7]
$var[fruit8]
$var[fruit9]
$var[fruit10]
]
$footer[Bloxfruits Stock | By Zubariel]

$else
Usage: \`!stock {normal or mirage}\`

$endif` },
  ],
  prev: { label: `voter-only command`, to: `/snippet/bdfd/voter-only` },
  next: { label: `clicking game`, to: `/snippet/bdfd/clicking` },
};

export function BloxfruitsStock() {
  return <SnippetDocShell doc={doc} />;
}
